basePath: /api
definitions:
  CambiarPassword:
    properties:
      Correo_electronico:
        type: string
      newpassword:
        type: string
      password:
        type: string
    required:
    - Correo_electronico
    - newpassword
    - password
    type: object
  Login:
    properties:
      Correo_electronico:
        type: string
      password:
        type: string
    required:
    - Correo_electronico
    - password
    type: object
  Perfil:
    properties:
      apellidos:
        type: string
      nombre:
        type: string
    required:
    - apellidos
    - nombre
    type: object
  Registro:
    properties:
      Correo_electronico:
        type: string
      apellidos:
        type: string
      celular:
        type: string
      codigo_pais:
        type: string
      fecha_nacimiento:
        type: string
      genero:
        type: string
      nacionalidad:
        type: string
      nombre:
        type: string
      password:
        type: string
      secret:
        type: string
    required:
    - Correo_electronico
    - apellidos
    - celular
    - codigo_pais
    - fecha_nacimiento
    - genero
    - nacionalidad
    - nombre
    - password
    - secret
    type: object
  Usuario:
    properties:
      Correo_electronico:
        type: string
      apellidos:
        type: string
      celular:
        type: string
      codigo_pais:
        type: string
      fecha_nacimiento:
        type: string
      genero:
        type: string
      nacionalidad:
        type: string
      nombre:
        type: string
    required:
    - Correo_electronico
    - apellidos
    - celular
    - codigo_pais
    - fecha_nacimiento
    - genero
    - nacionalidad
    - nombre
    type: object
  ValidarPassword:
    properties:
      Correo_electronico:
        type: string
      password:
        type: string
      secret:
        type: string
    required:
    - Correo_electronico
    - password
    - secret
    type: object
host: localhost:8080
info:
  contact: {}
  description: List of all api services
  title: Api urls for Unity Application
  version: "1.0"
paths:
  /api/recover:
    post:
      description: Permite recuperar la contrase単a mediante la clave unica
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ValidarPassword'
      summary: Recuperar Contrase単a
      tags:
      - Usuario
  /api/v1/usuario/change-password:
    post:
      description: Permite cambiar la contrase単a mediante el ingreso de la clave anterior
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CambiarPassword'
      security:
      - Bearer: []
      summary: Cambiar la Contrase単a
      tags:
      - Usuario
  /api/v1/usuario/update-perfild:
    post:
      description: Permite cambiar los datos del perfil del usuario
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Perfil'
      security:
      - Bearer: []
      summary: Cambiar los datos del perfil
      tags:
      - Usuario
  /auth/login:
    post:
      description: Autentificar usuario
      parameters:
      - description: Autentificar Usuario
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Login Usuario
      tags:
      - Usuario
  /auth/register:
    post:
      description: Guardar nuevo usuario
      parameters:
      - description: Create User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/Registro'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Registrar Usuario
      tags:
      - Usuario
  /v1/list:
    get:
      description: Listado de usuarios
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Usuario'
            type: array
      security:
      - Bearer: []
      summary: Listado de Usuarios
      tags:
      - Usuario
  /v1/user:
    get:
      description: Obtener los datos del usuario por su id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Usuario'
      summary: Obtener Usuario por Id
      tags:
      - Usuario
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
